"""Initial migration.

Revision ID: 037392d2de5f
Revises: ea25cb11d687
Create Date: 2023-06-19 15:02:29.451999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037392d2de5f'
down_revision = 'ea25cb11d687'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_phone_no_key', type_='unique')
        batch_op.drop_column('phone_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.create_unique_constraint('users_phone_no_key', ['phone_no'])

    # ### end Alembic commands ###
