"""Initial migration.

Revision ID: 088f64c0823f
Revises: 
Create Date: 2023-06-09 08:36:51.819739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '088f64c0823f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('needs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('history_id', sa.String(length=60), nullable=False))
        batch_op.create_foreign_key(None, 'history', ['history_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('pay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=60), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('needs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('history_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
