"""Initial migration.

Revision ID: 120d609a755b
Revises: 037392d2de5f
Create Date: 2023-06-21 08:36:41.409317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120d609a755b'
down_revision = '037392d2de5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=160), nullable=False))
        batch_op.add_column(sa.Column('phone_no', sa.String(length=60), nullable=False))
        batch_op.create_unique_constraint(None, ['phone_no'])
        batch_op.drop_column('google_id')
        batch_op.drop_column('email')
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=260), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=260), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('google_id', sa.VARCHAR(length=260), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('phone_no')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
