"""Initial migration.

Revision ID: 473834128059
Revises: e1efeaf6f6f0
Create Date: 2023-06-12 10:50:02.914046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473834128059'
down_revision = 'e1efeaf6f6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_no',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('phone_no',
               existing_type=sa.String(length=60),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
