"""Initial migration.

Revision ID: 920917ea827f
Revises: cde6ca618c23
Create Date: 2023-06-16 12:45:03.493268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '920917ea827f'
down_revision = 'cde6ca618c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=60), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('needs', schema=None) as batch_op:
        batch_op.drop_constraint('needs_history_id_fkey', type_='foreignkey')
        batch_op.drop_column('history_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('needs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('history_id', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('needs_history_id_fkey', 'history', ['history_id'], ['id'])

    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
