"""Initial migration.

Revision ID: 95aa3df63d16
Revises: 4471858e3be0
Create Date: 2023-06-23 06:23:00.450583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95aa3df63d16'
down_revision = '4471858e3be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('needs', schema=None) as batch_op:
        batch_op.drop_constraint('needs_phone_no_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('needs', schema=None) as batch_op:
        batch_op.create_unique_constraint('needs_phone_no_key', ['phone_no'])

    # ### end Alembic commands ###
