"""Initial migration.

Revision ID: c1d4e6e30866
Revises: 120d609a755b
Create Date: 2023-06-21 09:26:37.867323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d4e6e30866'
down_revision = '120d609a755b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=60), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
