"""Initial migration.

Revision ID: e1efeaf6f6f0
Revises: 26327b72253f
Create Date: 2023-06-12 10:28:22.954449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1efeaf6f6f0'
down_revision = '26327b72253f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_no', sa.Integer(), nullable=False))
        batch_op.drop_constraint('users_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['phone_no'])
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('users_email_key', ['email'])
        batch_op.drop_column('phone_no')

    # ### end Alembic commands ###
