"""Initial migration.

Revision ID: ea25cb11d687
Revises: 920917ea827f
Create Date: 2023-06-19 14:59:03.236287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea25cb11d687'
down_revision = '920917ea827f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=260), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=260), nullable=False))
        batch_op.add_column(sa.Column('avatar_url', sa.String(length=260), nullable=False))
        batch_op.drop_column('username')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=260), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
        batch_op.drop_column('avatar_url')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
